Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8088
  
  #define rede privada (só o host pode acessar) com ip estático
  #config.vm.network "private_network", ip: "192.168.50.4"

  #dhcp serve para determinar ips para maquinas automaticamente
  #config.vm.network "private_network", type: "dhcp"
  
  #rede publica (bridge). Se o ip não for definido, o será pelo dhcp do host
  config.vm.network "public_network", ip: "192.168.15.24"
end
