---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: [
          'php5', 
          'apache2', 
          'libapache2-mod-php5', #integração php-apache 
          'php5-gd', 
          'libssh2-php',
          'php5-mcrypt',
          'mysql-server-5.6',
          'python-mysqldb', #necessario pelo ansible, para executar modulos de db
          'php5-mysql']
        state: latest
      become: yes

    - name: 'Cria o banco de dados'
      #nome do modulo. outros bd's possuem modulos diferentes
      mysql_db: 
        name: wordpress_db
        login_user: root
        #login_password:
        state: present #cria o banco; absent:destroy; dump; import sql
    
    - name: 'Cria usuário no mysql'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 123456
        priv: 'wordpress_db.*:ALL'
        state: present
