---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: [
          'mysql-server-5.6',
          'python-mysqldb', #necessario pelo ansible, para executar modulos de db
          ]
        state: latest
      become: yes

    - name: 'Cria o banco de dados'
      #nome do modulo. outros bd's possuem modulos diferentes
      mysql_db: 
        name: wordpress_db
        login_user: root
        #login_password:
        state: present #cria o banco; absent:destroy; dump; import sql
    
    - name: 'Cria usuário no mysql'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 123456
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '172.0.0.1'
        - '172.16.0.10'

    - name: 'Configura apache para servir o wordpress'
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/my.cnf'
      become: yes
      notify: 
        - restart mysql 


- hosts: wordpress

  handlers:
    - name: 'restart apache'
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: [
          'php5', 
          'apache2', 
          'libapache2-mod-php5', #integração php-apache 
          'php5-gd', 
          'libssh2-php',
          'php5-mcrypt',
          'php5-mysql']
        state: latest
      become: yes
  
    - name: 'Baixa o arquivo de instalação do wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompact o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes

    - name: 'Copia arquivo de exemplo do wordpress'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes #tudo feito na maquina alvo
      become: yes

    - name: 'Configura wp-config com as entradas do banco de dados'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_use' }
        - { regex: 'password_here', value: '123456' }
        - { regex: 'localhost', value: '172.16.0.11' }
      become: yes
    
    - name: 'Configura apache para servir o wordpress'
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify: 
        - restart apache
