Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

  config.vm.define "wordpress" do |wp|
    wp.vm.network "private_network", ip: "172.16.0.10"
  end

  config.vm.define "mysql" do |wp|
    wp.vm.network "private_network", ip: "172.16.0.11"
  end
end
